### ISSUE TITLE
No 'Click' on Android

### ISSUE THREAD

**Issue by cosnofski** [MatiMenich/cordova-plugin-nativeClickSound#2]
This plugin is working fine on iOS but not on Android. On Android, nativeclick appears to be defined but I don't hear anything. The error callback isn't triggered either. Please advise.

"platform": "Android",
  "version": "6.0.1",
  "cordova": "4.1.1",
  "model": "Nexus 5X",
"manufacturer": "LGE",

cordova-plugin-crosswalk-webview 1.5.0

Thanks

**Comment by cosnofski** [comment]
Sorry, I had touch sounds disabled! Working now.

**Comment by MatiMenich** [comment]
Glad it's working then 😄
