### ISSUE TITLE
cordova-plugin-nativeClickSound in Ionic

### ISSUE THREAD

**Issue by noveltys** [MatiMenich/cordova-plugin-nativeClickSound#3]
Hi,
how do i had cordova-plugin-nativeClickSound in a Ionic project, please ? I mean after installation.

Thank you.

EDIT: Got it. Works fine. Thanks for the plugin. :)

**Comment by MatiMenich** [comment]
Sorry I was very busy this days, glad you've figured out!

Closing this issue then.
